export const API_ENDPOINTS = {
  PRODUCTS: '/product',
  CART: '/cart',
  AUTH: '/auth',
  ADMIN: {
    BASE: '/admin',
    STATS: '/admin/stats',
    ORDERS: '/admin/orders',
    USERS: '/admin/users',
    BANNERS: '/admin/banners',
    PRODUCTS: '/admin/products',
  },
  ORDERS: '/order',
  CATEGORIES: '/category',
  REVIEWS: '/review',
  WISHLIST: '/wish/user/wishlist',
  SELLER: '/seller',
  USER: '/user',
  PAYMENT: '/payment',
};
