export const API_ENDPOINTS = {
  PRODUCTS: '/product',
  CART: '/cart',
  AUTH: '/auth',
  ADMIN: {
    BASE: '/admin',
    STATS: '/admin/stats',
    ANALYTICS: '/admin/analytics',
    ORDERS: '/admin/orders',
    USERS: '/admin/users',
    SELLERS: '/admin/sellers',
    PRODUCTS: '/admin/products',
    COUPONS: '/admin/coupons',
    REVIEWS: '/admin/reviews',
    BANNERS: '/admin/banners',
  },
  ORDERS: '/order',
  CATEGORIES: '/category',
  REVIEWS: '/review',
  WISHLIST: '/wish/user/wishlist',
  SELLER: '/seller',
  USER: '/user',
  PAYMENT: '/payment',
};
