// ─────────────────────────────────────────────────────────────────────────────
// category.model.ts
//
// Covers: Product categories from the /category endpoint.
// Used by: CategoryService, ProductListComponent (filter dropdown),
//          AdminCategoriesComponent, HomepageComponent (category grid).
// ─────────────────────────────────────────────────────────────────────────────

import { CloudinaryImage } from './shared.model';

/**
 * A product category as returned by the backend.
 *
 * Categories support nesting: a category can optionally have a parentCategoryId,
 * making it a subcategory. Example:
 *   "Electronics" (no parent) → top-level category
 *   "Smartphones" (parentCategoryId: Electronics._id) → subcategory
 *
 * The frontend uses this to build the category navigation tree on the homepage
 * and in the product listing filter sidebar.
 */
export interface Category {
  _id: string;

  name: string;

  // URL-friendly version of the name, generated by the backend.
  // "Home Electronics" → "home-electronics"
  slug: string;

  description?: string;

  image: CloudinaryImage;

  // Optional: only present for subcategories.
  // If this is undefined, the category is a top-level category.
  parentCategoryId?: string;

  // The admin user who created this category
  createdBy: string;

  createdAt: string;
  updatedAt?: string;
}

// ─── Request Payloads ─────────────────────────────────────────────────────────

/**
 * Data sent to POST /category when creating a new category.
 * The image file itself is appended to FormData separately in the service —
 * it cannot be represented in a plain JSON interface.
 */
export interface CreateCategoryPayload {
  name: string;
  description?: string;
  // Optional: include to make this a subcategory of an existing category
  parentCategoryId?: string;
}

/**
 * When updating a category, both fields are optional.
 * You can update just the name, just the image, or both.
 */
export interface UpdateCategoryPayload {
  name?: string;
  description?: string;
  // The image file is handled via FormData — not included here
}

// ─── Response Shapes ──────────────────────────────────────────────────────────

/**
 * Response from GET /category — returns all categories as a flat list.
 * The frontend is responsible for building a nested tree from this list
 * if needed (by grouping categories with the same parentCategoryId).
 */
export interface CategoriesResponse {
  message: string;
  categories: Category[];
}

/**
 * Response from GET /category/:id, POST /category, PATCH /category/:id.
 */
export interface CategoryResponse {
  message: string;
  category: Category;
}
