// ─────────────────────────────────────────────────────────────────────────────
// product.model.ts
//
// Covers: All product-related data shapes from the /product endpoint.
// Used by: ProductService, ProductListComponent, ProductDetailComponent,
//          ProductCardComponent, CartService (references product price),
//          SellerService (seller's own products), AdminService (admin products).
// ─────────────────────────────────────────────────────────────────────────────

import { CloudinaryImage, Pagination } from './shared.model';
import { Review } from './review.model';
import { Category } from './category.model';

/**
 * The full Product object as returned by the backend.
 * Every field here maps directly to what GET /product/:id returns.
 *
 * Key design decisions worth understanding:
 *  - `price` is the raw price before discount
 *  - `finalPrice` is what the backend already calculated after applying discount
 *    → Use finalPrice for displaying prices and cart calculations
 *    → Use price + discount only when showing "was/now" pricing
 *  - `isDeleted` is always present because the backend uses soft delete.
 *    Deleted products still exist in the database — they just have isDeleted: true.
 *    The public GET /product endpoint filters these out, but the admin endpoint
 *    returns them so admins can recover them.
 */
export interface Product {
  _id: string;

  title: string;

  // URL-friendly version of the title, generated by the backend.
  // "iPhone 14 Pro" → "iphone-14-pro"
  // Can be used for SEO-friendly URLs if the backend supports it.
  slug: string;

  // Optional because the backend marks it as optional in the contract
  description?: string;

  // The original price before any discount is applied
  price: number;

  // The discount percentage (0–100). Optional because not all products
  // are discounted. A product with no discount simply has no discount field.
  discount?: number;

  // The price after discount, pre-calculated by the backend.
  // Formula: finalPrice = price - (price * discount / 100)
  // Always use this field when displaying prices to users.
  finalPrice: number;

  stock: number;

  // The average of all review ratings for this product (0 when no reviews yet)
  avgRating: number;

  mainImage: CloudinaryImage;

  // Additional product images — optional, up to 5 per the API contract
  images?: CloudinaryImage[];

  // The MongoDB ObjectId of the seller who created this product.
  // Used to determine edit/delete permissions on the frontend.
  sellerId: string;

  // The MongoDB ObjectId of this product's category.
  // The product listing page uses this for category filtering.
  category: Category;

  // Soft-delete flag. When true, the product is "deleted" but still in the DB.
  // Admin endpoints return products where isDeleted is true so they can be recovered.
  isDeleted: boolean;

  createdAt: string;
  updatedAt?: string;

  // Only present when fetching a single product (GET /product/:id).
  // The backend populates this field with the product's reviews.
  // It is optional because the list endpoint (GET /product) does NOT populate it —
  // that would be far too much data for a paginated list of 10+ products.
  reviews?: Review[];
}

// ─── Request Payloads ─────────────────────────────────────────────────────────

/**
 * The data sent when creating a new product.
 * Note: image files (mainImage, subImages) are handled via FormData separately —
 * they are NOT part of this interface because files cannot be typed as strings.
 * The ProductService.create() method accepts a FormData object directly.
 */
export interface CreateProductPayload {
  title: string;
  description?: string;
  price: number;
  discount?: number;
  stock: number;
  categoryId: string;
}

/**
 * When updating a product, every field is optional —
 * you only send what you want to change.
 * Partial<CreateProductPayload> generates { title?: string, price?: number, ... }
 * automatically from the create payload above.
 */
export type UpdateProductPayload = Partial<CreateProductPayload>;

/**
 * Query parameters accepted by GET /product.
 * All optional — the backend applies sensible defaults when omitted.
 */
export interface ProductQueryParams {
  search?: string;
  minPrice?: string;
  maxPrice?: string;
  categoryId?: string;
  // Sort field. Prefix with '-' for descending. e.g. '-createdAt' = newest first
  sort?: string;
  page?: string;
  limit?: string;
}

// ─── Response Shapes ──────────────────────────────────────────────────────────

/**
 * Response from GET /product (the paginated list endpoint).
 * The pagination object tells the component how many pages exist
 * so it can render the correct number of page buttons.
 */
export interface ProductsResponse {
  message: string;
  products: Product[];
  pagination: Pagination;
}

/**
 * Response from GET /product/:id, POST /product, PATCH /product/:id.
 * A single product wrapped in a message. The product from GET /product/:id
 * will have its reviews array populated; others will not.
 */
export interface ProductResponse {
  message: string;
  product: Product;
}
